# Generated by Django 2.2.6 on 2019-10-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReport',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=100)),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
